//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WCFConsumption.ServiceReferenceServicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Select_TipoServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Select_TipoServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoServicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoServicio {
            get {
                return this.IdTipoServicioField;
            }
            set {
                if ((this.IdTipoServicioField.Equals(value) != true)) {
                    this.IdTipoServicioField = value;
                    this.RaisePropertyChanged("IdTipoServicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Select_Ubicacion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Select_Ubicacion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMaestroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMaestro {
            get {
                return this.IdMaestroField;
            }
            set {
                if ((this.IdMaestroField.Equals(value) != true)) {
                    this.IdMaestroField = value;
                    this.RaisePropertyChanged("IdMaestro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUbicacion {
            get {
                return this.IdUbicacionField;
            }
            set {
                if ((this.IdUbicacionField.Equals(value) != true)) {
                    this.IdUbicacionField = value;
                    this.RaisePropertyChanged("IdUbicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="verServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class verServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Coste_BaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_de_ServicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Coste_Base {
            get {
                return this.Coste_BaseField;
            }
            set {
                if ((this.Coste_BaseField.Equals(value) != true)) {
                    this.Coste_BaseField = value;
                    this.RaisePropertyChanged("Coste_Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_de_Servicio {
            get {
                return this.Nombre_de_ServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_de_ServicioField, value) != true)) {
                    this.Nombre_de_ServicioField = value;
                    this.RaisePropertyChanged("Nombre_de_Servicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="verClientes_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class verClientes_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="verClientesActivos_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class verClientesActivos_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_de_UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_de_Ubicacion {
            get {
                return this.Tipo_de_UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_de_UbicacionField, value) != true)) {
                    this.Tipo_de_UbicacionField = value;
                    this.RaisePropertyChanged("Tipo_de_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_In_TipoServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_In_TipoServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_In_Ubicacion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_In_Ubicacion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_In_Servicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_In_Servicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_In_Cliente_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_In_Cliente_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Up_TipoServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Up_TipoServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Up_Ubicacion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Up_Ubicacion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Up_Servicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Up_Servicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Up_Cliente_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Up_Cliente_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Del_TipoServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Del_TipoServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Del_Ubicacion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Del_Ubicacion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Del_Servicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Del_Servicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_Del_Cliente_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_Del_Cliente_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_selectOne_TipoServicio_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class SP_selectOne_TipoServicio_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoServicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoServicio {
            get {
                return this.IdTipoServicioField;
            }
            set {
                if ((this.IdTipoServicioField.Equals(value) != true)) {
                    this.IdTipoServicioField = value;
                    this.RaisePropertyChanged("IdTipoServicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceServicios.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListTipoServicio", ReplyAction="http://tempuri.org/IService1/viewListTipoServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_TipoServicio_Result[] viewListTipoServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListTipoServicio", ReplyAction="http://tempuri.org/IService1/viewListTipoServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_TipoServicio_Result[]> viewListTipoServicioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListUbicacion", ReplyAction="http://tempuri.org/IService1/viewListUbicacionResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_Ubicacion_Result[] viewListUbicacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListUbicacion", ReplyAction="http://tempuri.org/IService1/viewListUbicacionResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_Ubicacion_Result[]> viewListUbicacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListServicio", ReplyAction="http://tempuri.org/IService1/viewListServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.verServicio_Result[] viewListServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListServicio", ReplyAction="http://tempuri.org/IService1/viewListServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verServicio_Result[]> viewListServicioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListClientes", ReplyAction="http://tempuri.org/IService1/viewListClientesResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.verClientes_Result[] viewListClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListClientes", ReplyAction="http://tempuri.org/IService1/viewListClientesResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verClientes_Result[]> viewListClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListClientesActivos", ReplyAction="http://tempuri.org/IService1/viewListClientesActivosResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.verClientesActivos_Result[] viewListClientesActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewListClientesActivos", ReplyAction="http://tempuri.org/IService1/viewListClientesActivosResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verClientesActivos_Result[]> viewListClientesActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertTipoServicio", ReplyAction="http://tempuri.org/IService1/insertTipoServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_In_TipoServicio_Result insertTipoServicio(string descripcion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertTipoServicio", ReplyAction="http://tempuri.org/IService1/insertTipoServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_TipoServicio_Result> insertTipoServicioAsync(string descripcion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertUbicacion", ReplyAction="http://tempuri.org/IService1/insertUbicacionResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Ubicacion_Result insertUbicacion(int maestro, string nombre, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertUbicacion", ReplyAction="http://tempuri.org/IService1/insertUbicacionResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Ubicacion_Result> insertUbicacionAsync(int maestro, string nombre, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertServicio", ReplyAction="http://tempuri.org/IService1/insertServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Servicio_Result insertServicio(int tipoServicio, string nombre, decimal costoBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertServicio", ReplyAction="http://tempuri.org/IService1/insertServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Servicio_Result> insertServicioAsync(int tipoServicio, string nombre, decimal costoBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertCliente", ReplyAction="http://tempuri.org/IService1/insertClienteResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Cliente_Result insertCliente(string nombre, string apellido, string telefono, string tipo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertCliente", ReplyAction="http://tempuri.org/IService1/insertClienteResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Cliente_Result> insertClienteAsync(string nombre, string apellido, string telefono, string tipo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateTipoServicio", ReplyAction="http://tempuri.org/IService1/updateTipoServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_TipoServicio_Result updateTipoServicio(int id, string descripcion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateTipoServicio", ReplyAction="http://tempuri.org/IService1/updateTipoServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_TipoServicio_Result> updateTipoServicioAsync(int id, string descripcion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUbicacion", ReplyAction="http://tempuri.org/IService1/updateUbicacionResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Ubicacion_Result updateUbicacion(int maestro, string nombre, string tipo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUbicacion", ReplyAction="http://tempuri.org/IService1/updateUbicacionResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Ubicacion_Result> updateUbicacionAsync(int maestro, string nombre, string tipo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateServicio", ReplyAction="http://tempuri.org/IService1/updateServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Servicio_Result updateServicio(int id, int tipoServicio, string nombre, decimal costoBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateServicio", ReplyAction="http://tempuri.org/IService1/updateServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Servicio_Result> updateServicioAsync(int id, int tipoServicio, string nombre, decimal costoBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCliente", ReplyAction="http://tempuri.org/IService1/updateClienteResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Cliente_Result updateCliente(int id, string nombre, string apellido, string telefono, string tipo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCliente", ReplyAction="http://tempuri.org/IService1/updateClienteResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Cliente_Result> updateClienteAsync(int id, string nombre, string apellido, string telefono, string tipo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteTipoServicio", ReplyAction="http://tempuri.org/IService1/deleteTipoServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_TipoServicio_Result deleteTipoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteTipoServicio", ReplyAction="http://tempuri.org/IService1/deleteTipoServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_TipoServicio_Result> deleteTipoServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUbicacion", ReplyAction="http://tempuri.org/IService1/deleteUbicacionResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Ubicacion_Result deleteUbicacion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUbicacion", ReplyAction="http://tempuri.org/IService1/deleteUbicacionResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Ubicacion_Result> deleteUbicacionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteServicio", ReplyAction="http://tempuri.org/IService1/deleteServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Servicio_Result deleteServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteServicio", ReplyAction="http://tempuri.org/IService1/deleteServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Servicio_Result> deleteServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCliente", ReplyAction="http://tempuri.org/IService1/deleteClienteResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Cliente_Result deleteCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCliente", ReplyAction="http://tempuri.org/IService1/deleteClienteResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Cliente_Result> deleteClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectOneTipoServicio", ReplyAction="http://tempuri.org/IService1/selectOneTipoServicioResponse")]
        MVC_WCFConsumption.ServiceReferenceServicios.SP_selectOne_TipoServicio_Result selectOneTipoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectOneTipoServicio", ReplyAction="http://tempuri.org/IService1/selectOneTipoServicioResponse")]
        System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_selectOne_TipoServicio_Result> selectOneTipoServicioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC_WCFConsumption.ServiceReferenceServicios.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC_WCFConsumption.ServiceReferenceServicios.IService1>, MVC_WCFConsumption.ServiceReferenceServicios.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_TipoServicio_Result[] viewListTipoServicio() {
            return base.Channel.viewListTipoServicio();
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_TipoServicio_Result[]> viewListTipoServicioAsync() {
            return base.Channel.viewListTipoServicioAsync();
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_Ubicacion_Result[] viewListUbicacion() {
            return base.Channel.viewListUbicacion();
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Select_Ubicacion_Result[]> viewListUbicacionAsync() {
            return base.Channel.viewListUbicacionAsync();
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.verServicio_Result[] viewListServicio() {
            return base.Channel.viewListServicio();
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verServicio_Result[]> viewListServicioAsync() {
            return base.Channel.viewListServicioAsync();
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.verClientes_Result[] viewListClientes() {
            return base.Channel.viewListClientes();
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verClientes_Result[]> viewListClientesAsync() {
            return base.Channel.viewListClientesAsync();
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.verClientesActivos_Result[] viewListClientesActivos() {
            return base.Channel.viewListClientesActivos();
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.verClientesActivos_Result[]> viewListClientesActivosAsync() {
            return base.Channel.viewListClientesActivosAsync();
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_In_TipoServicio_Result insertTipoServicio(string descripcion, bool estado) {
            return base.Channel.insertTipoServicio(descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_TipoServicio_Result> insertTipoServicioAsync(string descripcion, bool estado) {
            return base.Channel.insertTipoServicioAsync(descripcion, estado);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Ubicacion_Result insertUbicacion(int maestro, string nombre, string tipo) {
            return base.Channel.insertUbicacion(maestro, nombre, tipo);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Ubicacion_Result> insertUbicacionAsync(int maestro, string nombre, string tipo) {
            return base.Channel.insertUbicacionAsync(maestro, nombre, tipo);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Servicio_Result insertServicio(int tipoServicio, string nombre, decimal costoBase) {
            return base.Channel.insertServicio(tipoServicio, nombre, costoBase);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Servicio_Result> insertServicioAsync(int tipoServicio, string nombre, decimal costoBase) {
            return base.Channel.insertServicioAsync(tipoServicio, nombre, costoBase);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Cliente_Result insertCliente(string nombre, string apellido, string telefono, string tipo, string estado) {
            return base.Channel.insertCliente(nombre, apellido, telefono, tipo, estado);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_In_Cliente_Result> insertClienteAsync(string nombre, string apellido, string telefono, string tipo, string estado) {
            return base.Channel.insertClienteAsync(nombre, apellido, telefono, tipo, estado);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_TipoServicio_Result updateTipoServicio(int id, string descripcion, bool estado) {
            return base.Channel.updateTipoServicio(id, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_TipoServicio_Result> updateTipoServicioAsync(int id, string descripcion, bool estado) {
            return base.Channel.updateTipoServicioAsync(id, descripcion, estado);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Ubicacion_Result updateUbicacion(int maestro, string nombre, string tipo, int id) {
            return base.Channel.updateUbicacion(maestro, nombre, tipo, id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Ubicacion_Result> updateUbicacionAsync(int maestro, string nombre, string tipo, int id) {
            return base.Channel.updateUbicacionAsync(maestro, nombre, tipo, id);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Servicio_Result updateServicio(int id, int tipoServicio, string nombre, decimal costoBase) {
            return base.Channel.updateServicio(id, tipoServicio, nombre, costoBase);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Servicio_Result> updateServicioAsync(int id, int tipoServicio, string nombre, decimal costoBase) {
            return base.Channel.updateServicioAsync(id, tipoServicio, nombre, costoBase);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Cliente_Result updateCliente(int id, string nombre, string apellido, string telefono, string tipo, string estado) {
            return base.Channel.updateCliente(id, nombre, apellido, telefono, tipo, estado);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Up_Cliente_Result> updateClienteAsync(int id, string nombre, string apellido, string telefono, string tipo, string estado) {
            return base.Channel.updateClienteAsync(id, nombre, apellido, telefono, tipo, estado);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_TipoServicio_Result deleteTipoServicio(int id) {
            return base.Channel.deleteTipoServicio(id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_TipoServicio_Result> deleteTipoServicioAsync(int id) {
            return base.Channel.deleteTipoServicioAsync(id);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Ubicacion_Result deleteUbicacion(int id) {
            return base.Channel.deleteUbicacion(id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Ubicacion_Result> deleteUbicacionAsync(int id) {
            return base.Channel.deleteUbicacionAsync(id);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Servicio_Result deleteServicio(int id) {
            return base.Channel.deleteServicio(id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Servicio_Result> deleteServicioAsync(int id) {
            return base.Channel.deleteServicioAsync(id);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Cliente_Result deleteCliente(int id) {
            return base.Channel.deleteCliente(id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_Del_Cliente_Result> deleteClienteAsync(int id) {
            return base.Channel.deleteClienteAsync(id);
        }
        
        public MVC_WCFConsumption.ServiceReferenceServicios.SP_selectOne_TipoServicio_Result selectOneTipoServicio(int id) {
            return base.Channel.selectOneTipoServicio(id);
        }
        
        public System.Threading.Tasks.Task<MVC_WCFConsumption.ServiceReferenceServicios.SP_selectOne_TipoServicio_Result> selectOneTipoServicioAsync(int id) {
            return base.Channel.selectOneTipoServicioAsync(id);
        }
    }
}
